### ISSUE TITLE
Can't join from 1.7

### ISSUE THREAD

**Issue by RedolentHalo** [Xernium/Travertine#1] opened 2023-02-19 05:26 UTC
![image](https://user-images.githubusercontent.com/86344714/219925764-e0c23bbf-c77a-4329-8989-b0e7da9f280f.png)
hey i am having issues joining from 1.7

**Comment by air-anchor** [comment] 2023-02-19 19:47
Tell me how to reproduce and I will try to fix.
What server version?
What client version?
Using ViaVersion + ViaRewind?

**Comment by RedolentHalo** [comment] 2023-02-22 14:30
Server version 1.8.9
1.7
Yes

**Comment by air-anchor** [comment] 2023-03-02 12:07
Cannot reproduce. Tried just about everything.
Use ViaVersion-dev and normal ViaRewind on server
**will not work if installed on proxy** and that wont be fixed. Is vias fault.

**Closed as completed by air-anchor** 2023-03-02 12:07 UTC
